name: t20-tue-simpeg

channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - ipywidgets>=0.6.0
  - mkl
  - discretize==0.7.0
  - simpeg==0.14.1
